#NOTE: heavy resource usage be careful and must have java runtime to run app
version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    ports: 
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - "./:/data"
    deploy:
      resources:
        limits:
          memory: 1.5G
          


  