apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
spec:
  type: NodePort
  #use selector to pick which pods to target 
  selector:
    app: accelerator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    #nodePort ranges from 30000-32767
    nodePort: 30007
  